site_name: Validador SemÃ¡ntico JurÃ­dico
repo_url: https://github.com/kabehz/validador-semantic
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  features:
    - navigation.tabs
    - search.highlight
    - navigation.top
    - content.code.copy
plugins:
  - search
  - tags
nav:
  - ğŸ—ï¸ Arquitectura: arquitectura.md
  - âš™ï¸ CI/CD: cicd.md
  - ğŸ’» CLI: cli.md
  - ğŸ³ Docker: docker.md
  - ğŸ  Inicio: index.md
  - ğŸ“œ Licencia: licencia.md
  - â˜¸ï¸ MicroK8s: microk8s.md
  - ğŸ§ª Tests: tests.md

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - assets/css/mermaid.css
  - assets/css/markdown.css
extra_js:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.0.2/mermaid.min.js
  - assets/js/mermaid.js

icon:
  logo: assets/images/logo.png
  title: Validador SemÃ¡ntico JurÃ­dico
  description: Herramienta para validar la semÃ¡ntica jurÃ­dica de documentos legales